# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1519243b971184c0c13f14d043ac8e0c818d6ac09df2f4e79ddfacdab23a1fcc4a18232b9353bf13d4f70c0546344cfc4c867277b019771a6d07b4c838c5624c

test:
  secret_key_base: aed57c9d128f14b95a28d0fe1ebd5d1cbe1cbe4f4c7412ec9bb0ca0405445a8d3e5006ed30c96da11981ebf42468b7efd9e01d48bbb6989043dd51e557d09fe8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
